name       : haskell-zlib-bindings
version    : 0.1.1.5
release    : 4
source     :
    - http://hackage.haskell.org/package/zlib-bindings-0.1.1.5/zlib-bindings-0.1.1.5.tar.gz : c83bb438f9b6c5fe860982731eb8ac7eff993e8b56cbc15ef5b471f229f79109
license    : BSD-3-Clause
component  : programming.haskell
summary    : Low-level bindings to the zlib package.
description: |
    Low-level bindings to the zlib package.
builddeps  :
    - haskell-cabal-install
    - haskell-zlib-devel
rundeps    :
    - devel:
        - haskell-zlib-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
